theme: minima
title: Yegor Wienski's blog
description: on programming languages, compilers, calculi and stuff

plugins:
  - jekyll-feed
  - jekyll-sitemap

twitter_username: mostwienski
rss: RSS Feed

comments_repo: wienski/wienski.github.io
