theme: minima
title: Yegor Wienski's blog

twitter_username: mostwienski
rss: rss

# plugin: jekyll-seo-tag
twitter:
  username: chad_baldwin
  card: summary_large_image

comments_repo: wienski/wienski.github.io
