theme: minima
title: Yegor Wienski's blog
author: Yegor Wienski
email: wienski@ya.ru
description: on programming languages, compilers, calculi and stuff

plugins:
  - jekyll-feed
  - jekyll-sitemap

twitter_username: mostwienski
rss: RSS Feed


show_excerpts: true # set to false to remove excerpts on the homepage
comments_repo: wienski/wienski.github.io
